services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    knp_menu_regex.voter:
        class: AppBundle\Menu\Voter\RequestVoter
        tags:
            - { name: knp_menu.voter, request: true }

    app.config:
        class: AppBundle\Services\Configuration
        arguments: ["@doctrine.orm.entity_manager"]

    user.profile.form.type:
        class: AppBundle\Form\ProfileFormType
        tags:
            - { name: form.type, alias: user_profile }

    user.event_listener:
        class: AppBundle\EventListener\UserListener
        arguments: ["@router"]
        tags:
            - { name: kernel.event_subscriber }

    facebook:
        class: AppBundle\Services\Facebook
        arguments: ["@doctrine.orm.entity_manager", %fb_app_id%, %fb_app_secret%, %fb_default_graph_version%, "@security.context", "@session"]
